from pathlib import Path

BASE = Path("/home/prime/arc_ai_angels")

AGENTS = {
    "lumeria": {
        "name": "lumeria",
        "path": BASE / "agents/omni/quantix/lead agent lumeria",
        "template_type": "custom_omni",
        "layer": "omni",
        "domain": "quantix/data-intelligence",
        "parent": "flux",
        "role": "Omni Lead / Data & Intelligence Domain Coordinator",
        "mission": "Ontvangt routed taken van Flux, beoordeelt Quantix-fit, verdeelt data-, research-, analyse- en intelligence-werk naar de juiste Quantix Sentinels, bewaakt kwaliteit en levert canon-conforme intelligence-output terug.",
    },
    "elora": {
        "name": "elora",
        "path": BASE / "agents/omni/quantix/sentinels/elora",
        "template_type": "custom_sentinel",
        "layer": "sentinel",
        "domain": "quantix/data-intelligence/research/elora",
        "parent": "lumeria",
        "role": "Research Sentinel",
        "mission": "Voert gerichte research uit binnen Quantix, verzamelt relevante signalen, bronnen en context en levert bruikbare onderzoeksoutput terug aan Lumeria.",
    },
    "kresta": {
        "name": "kresta",
        "path": BASE / "agents/omni/quantix/sentinels/kresta",
        "template_type": "custom_sentinel",
        "layer": "sentinel",
        "domain": "quantix/data-intelligence/analytics/kresta",
        "parent": "lumeria",
        "role": "Analytics Sentinel",
        "mission": "Analyseert datasets, patronen en prestaties binnen Quantix en levert onderbouwde analytische output terug aan Lumeria.",
    },
    "luvia": {
        "name": "luvia",
        "path": BASE / "agents/omni/quantix/sentinels/luvia",
        "template_type": "custom_sentinel",
        "layer": "sentinel",
        "domain": "quantix/data-intelligence/forecasting/luvia",
        "parent": "lumeria",
        "role": "Forecasting Sentinel",
        "mission": "Maakt voorspellingen, scenario-analyses en trendprojecties binnen Quantix en levert bruikbare forecast-output terug aan Lumeria.",
    },
    "nura": {
        "name": "nura",
        "path": BASE / "agents/omni/quantix/sentinels/nura",
        "template_type": "custom_sentinel",
        "layer": "sentinel",
        "domain": "quantix/data-intelligence/knowledge/nura",
        "parent": "lumeria",
        "role": "Knowledge Sentinel",
        "mission": "Bewaakt kennisstructuur, definities, semantische samenhang en intelligence-consistentie binnen Quantix en levert bruikbare kennisoutput terug aan Lumeria.",
    },
    "vondra": {
        "name": "vondra",
        "path": BASE / "agents/omni/quantix/sentinels/vondra",
        "template_type": "custom_sentinel",
        "layer": "sentinel",
        "domain": "quantix/data-intelligence/signals/vondra",
        "parent": "lumeria",
        "role": "Signals Sentinel",
        "mission": "Detecteert signalen, afwijkingen, kansen en risico-indicatoren binnen Quantix en levert bruikbare signal-output terug aan Lumeria.",
    },
    "fluentia": {
        "name": "fluentia",
        "path": BASE / "agents/omni/zenix/lead agent fluentia",
        "template_type": "custom_omni",
        "layer": "omni",
        "domain": "zenix/language-communication",
        "parent": "flux",
        "role": "Omni Lead / Language & Communication Domain Coordinator",
        "mission": "Ontvangt routed taken van Flux, beoordeelt Zenix-fit, verdeelt taal-, content-, messaging- en communicatie-werk naar de juiste Zenix Sentinels, bewaakt kwaliteit en levert canon-conforme communicatie-output terug.",
    },
    "draven": {
        "name": "draven",
        "path": BASE / "agents/omni/zenix/sentinels/draven",
        "template_type": "custom_sentinel",
        "layer": "sentinel",
        "domain": "zenix/language-communication/copy/draven",
        "parent": "fluentia",
        "role": "Copy Sentinel",
        "mission": "Schrijft en verfijnt overtuigende copy binnen Zenix en levert bruikbare tekstoutput terug aan Fluentia.",
    },
    "orizon": {
        "name": "orizon",
        "path": BASE / "agents/omni/zenix/sentinels/orizon",
        "template_type": "custom_sentinel",
        "layer": "sentinel",
        "domain": "zenix/language-communication/strategy/orizon",
        "parent": "fluentia",
        "role": "Messaging Strategy Sentinel",
        "mission": "Ontwikkelt messaging-structuur, positionering en communicatierichting binnen Zenix en levert bruikbare strategische communicatie-output terug aan Fluentia.",
    },
    "solis": {
        "name": "solis",
        "path": BASE / "agents/omni/zenix/sentinels/solis",
        "template_type": "custom_sentinel",
        "layer": "sentinel",
        "domain": "zenix/language-communication/storytelling/solis",
        "parent": "fluentia",
        "role": "Storytelling Sentinel",
        "mission": "Ontwikkelt narratief, verhaallijnen en merkverhaal binnen Zenix en levert bruikbare storytelling-output terug aan Fluentia.",
    },
    "unia": {
        "name": "unia",
        "path": BASE / "agents/omni/zenix/sentinels/unia",
        "template_type": "custom_sentinel",
        "layer": "sentinel",
        "domain": "zenix/language-communication/editorial/unia",
        "parent": "fluentia",
        "role": "Editorial Sentinel",
        "mission": "Bewerkt, verscherpt en harmoniseert tekstkwaliteit binnen Zenix en levert redactioneel sterke output terug aan Fluentia.",
    },
    "zena": {
        "name": "zena",
        "path": BASE / "agents/omni/zenix/sentinels/zena",
        "template_type": "custom_sentinel",
        "layer": "sentinel",
        "domain": "zenix/language-communication/localization/zena",
        "parent": "fluentia",
        "role": "Localization Sentinel",
        "mission": "Bewaakt taaladaptatie, toonconsistentie en doelgroepgeschikte lokalisatie binnen Zenix en levert bruikbare localization-output terug aan Fluentia.",
    },
}

PROTECTED_TEMPLATE_TYPES = {
    "lumeria": "custom_omni",
    "elora": "custom_sentinel",
    "kresta": "custom_sentinel",
    "luvia": "custom_sentinel",
    "nura": "custom_sentinel",
    "vondra": "custom_sentinel",
    "fluentia": "custom_omni",
    "draven": "custom_sentinel",
    "orizon": "custom_sentinel",
    "solis": "custom_sentinel",
    "unia": "custom_sentinel",
    "zena": "custom_sentinel",
}

