graph TD
    SF[Supreme Fea<br/>Architect & Eigenaar]
    N[Nova<br/>Consigliere / Silver Surfer]
    F[Flux<br/>Underboss / Brain]
    C[Cortexia<br/>Helix Lead]
    FI[Finoria<br/>Finix Lead]
    S[Saelia<br/>Matrix Lead]
    L[Lumeria<br/>Quantix Lead]
    FL[Fluentia<br/>Zenix Lead]
    HS[5x Helix Sentinels]
    FIS[5x Finix Sentinels]
    MS[5x Matrix Sentinels]
    QS[5x Quantix Sentinels]
    ZS[5x Zenix Sentinels]
    SF --> N
    N --> F
    F --> C
    F --> FI
    F --> S
    F --> L
    F --> FL
    C --> HS
    FI --> FIS
    S --> MS
    L --> QS
    FL --> ZS
