graph TD
    F[Flux]
    C[Cortexia L4] --> FO[Forge L4]
    C --> NE[Nero L4]
    C --> VE[Ventura L3]
    C --> AX[Axon L3]
    C --> CL[Clio L2]
    FI[Finoria L4] --> VE2[Vector L3]
    FI --> KA[Kairo L3]
    FI --> KE[Kenzo L2]
    FI --> OD[Odis L2]
    FI --> ZI[Zion L1]
    SA[Saelia L3] --> TH[Tharos L3]
    SA --> SO[Sora L3]
    SA --> AR[Arix L2]
    SA --> EN[Enki L2]
    SA --> DA[Daxio L2]
    LU[Lumeria L3] --> KR[Kresta L3]
    LU --> EL[Elora L2]
    LU --> LV[Luvia L3]
    LU --> NU[Nura L2]
    LU --> VO[Vondra L2]
    FL[Fluentia L3] --> DR[Draven L3]
    FL --> SL[Solis L3]
    FL --> OR[Orizon L3]
    FL --> UN[Unia L2]
    FL --> ZE[Zena L1]
    F --> C
    F --> FI
    F --> SA
    F --> LU
    F --> FL
